name: Publish Pkg
on:
  push:
    branches:
      - main
      - test-ci

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get submodules
        run: git submodule update --init --recursive
      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          SUPABASE_KEY: ${{secrets.SUPABASE_KEY}}
        run: |
          # npm config set //npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          bun run publish
